services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
    volumes:
      - ./elk/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elastic

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.2.4
    volumes:
      - ./elk/logstash/data:/usr/share/logstash/data
      - ./elk/logstash/config:/usr/share/logstash/config
      - ./elk/logstash/template:/usr/share/logstash/template
      - ./elk/logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elastic
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.4 
    volumes:
      - ./elk/kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    networks:
      - elastic
    depends_on:
      - elasticsearch

  cerebro:
    image: yannart/cerebro
    ports:
      - "9010:9000"
    networks:
      - elastic
    depends_on:
      - elasticsearch

networks:
  elastic:
    driver: bridge
