# https://github.com/elastic/elasticsearch-docker/blob/master/build/elasticsearch/elasticsearch.yml

cluster.name: "docker-cluster"
network.host: 0.0.0.0

# https://github.com/elastic/elasticsearch/pull/17288
discovery.zen.minimum_master_nodes: 1

# https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html

discovery.type: single-node

path.repo: ["/usr/share/elasticsearch/data/snapshots"]
